type standards.norm.dif
type standards.ac.dif
type standards.nac.dif
type standards.t.dif
type standards.nt.dif
type standards.pv.dif
type standards.npv.dif
type standards.rc.dif
type standards.nrc.dif
type standards.oc.dif
type standards.noc.dif
type standards.cc.dif
type standards.ncc.dif
type standards.clcl.dif
type standards.nclcl.dif
type standards.cgbl.dif
type standards.ncgbl.dif
type standards.bi.dif
type standards.nbi.dif
type standards.sls.dif
type standards.nsls.dif
type standards.url.dif
type standards.nurl.dif
type standards.fco.dif
type standards.nfco.dif
type standards.cfc.dif
type standards.ncfc.dif
type standards.dce.dif
type standards.ndce.dif
type standards.b2j.dif
type standards.nb2j.dif
type standards.rur.dif
type standards.nrur.dif
type standards.npc.dif
type standards.nnpc.dif
