{******************************************************************************
*                                                                             *
*                         WINDOWS SUPPORT ROUTINES                            *
*                                                                             *
*                        Copyright (C) 2001 S. A. Moore                       *
*                                                                             *
******************************************************************************}

module winsup;

uses stddef;

{ get windows error string }

procedure geterr(e: integer; var p: pstring);

{ copy string }

procedure copy(var  d: pstring; view s: string);

begin

   new(d, max(s)); { create destination }
   d^ := s { copy string }

end;

begin

   case e of { error }

      0:    copy(p, 'No error');
      1:    copy(p, 'Invalid function');
      2:    copy(p, 'File not found');
      3:    copy(p, 'Path not found');
      4:    copy(p, 'Too many open files');
      5:    copy(p, 'Access denied');
      6:    copy(p, 'Invalid handle');
      7:    copy(p, 'Arena trashed');
      8:    copy(p, 'Not enough memory');
      9:    copy(p, 'Invalid block');
      10:   copy(p, 'Bad environment');
      11:   copy(p, 'Bad format');
      12:   copy(p, 'Invalid access');
      13:   copy(p, 'Invalid data');
      14:   copy(p, 'Outofmemory');
      15:   copy(p, 'Invalid drive');
      16:   copy(p, 'Current directory');
      17:   copy(p, 'Not same device');
      18:   copy(p, 'No more files');
      19:   copy(p, 'Write protect');
      20:   copy(p, 'Bad unit');
      21:   copy(p, 'Not ready');
      22:   copy(p, 'Bad command');
      23:   copy(p, 'Crc');
      24:   copy(p, 'Bad length');
      25:   copy(p, 'Seek');
      26:   copy(p, 'Not dos disk');
      27:   copy(p, 'Sector not found');
      28:   copy(p, 'Out of paper');
      29:   copy(p, 'Write fault');
      30:   copy(p, 'Read fault');
      31:   copy(p, 'Gen failure');
      32:   copy(p, 'Sharing violation');
      33:   copy(p, 'Lock violation');
      34:   copy(p, 'Wrong disk');
      36:   copy(p, 'Sharing buffer exceeded');
      38:   copy(p, 'Handle eof');
      39:   copy(p, 'Handle disk full');
      50:   copy(p, 'Not supported');
      51:   copy(p, 'Rem not list');
      52:   copy(p, 'Dup name');
      53:   copy(p, 'Bad netpath');
      54:   copy(p, 'Network busy');
      55:   copy(p, 'Dev not exist');
      56:   copy(p, 'Too many cmds');
      57:   copy(p, 'Adap hdw err');
      58:   copy(p, 'Bad net resp');
      59:   copy(p, 'Unexp net err');
      60:   copy(p, 'Bad rem adap');
      61:   copy(p, 'Printq full');
      62:   copy(p, 'No spool space');
      63:   copy(p, 'Print cancelled');
      64:   copy(p, 'Netname deleted');
      65:   copy(p, 'Network access denied');
      66:   copy(p, 'Bad dev type');
      67:   copy(p, 'Bad net name');
      68:   copy(p, 'Too many names');
      69:   copy(p, 'Too many sess');
      70:   copy(p, 'Sharing paused');
      71:   copy(p, 'Req not accep');
      72:   copy(p, 'Redir paused');
      80:   copy(p, 'File exists');
      82:   copy(p, 'Cannot make');
      83:   copy(p, 'Fail i24');
      84:   copy(p, 'Out of structures');
      85:   copy(p, 'Already assigned');
      86:   copy(p, 'Invalid password');
      87:   copy(p, 'Invalid parameter');
      88:   copy(p, 'Net write fault');
      89:   copy(p, 'No proc slots');
      100:  copy(p, 'Too many semaphores');
      101:  copy(p, 'Excl sem already owned');
      102:  copy(p, 'Sem is set');
      103:  copy(p, 'Too many sem requests');
      104:  copy(p, 'Invalid at interrupt time');
      105:  copy(p, 'Sem owner died');
      106:  copy(p, 'Sem user limit');
      107:  copy(p, 'Disk change');
      108:  copy(p, 'Drive locked');
      109:  copy(p, 'Broken pipe');
      110:  copy(p, 'Open failed');
      111:  copy(p, 'Buffer overflow');
      112:  copy(p, 'Disk full');
      113:  copy(p, 'No more search handles');
      114:  copy(p, 'Invalid target handle');
      117:  copy(p, 'Invalid category');
      118:  copy(p, 'Invalid verify switch');
      119:  copy(p, 'Bad driver level');
      120:  copy(p, 'Call not implemented');
      121:  copy(p, 'Sem timeout');
      122:  copy(p, 'Insufficient buffer');
      123:  copy(p, 'Invalid name');
      124:  copy(p, 'Invalid level');
      125:  copy(p, 'No volume label');
      126:  copy(p, 'Mod not found');
      127:  copy(p, 'Proc not found');
      128:  copy(p, 'Wait no children');
      129:  copy(p, 'Child not complete');
      130:  copy(p, 'Direct access handle');
      131:  copy(p, 'Negative seek');
      132:  copy(p, 'Seek on device');
      133:  copy(p, 'Is join target');
      134:  copy(p, 'Is joined');
      135:  copy(p, 'Is substed');
      136:  copy(p, 'Not joined');
      137:  copy(p, 'Not substed');
      138:  copy(p, 'Join to join');
      139:  copy(p, 'Subst to subst');
      140:  copy(p, 'Join to subst');
      141:  copy(p, 'Subst to join');
      142:  copy(p, 'Busy drive');
      143:  copy(p, 'Same drive');
      144:  copy(p, 'Dir not root');
      145:  copy(p, 'Dir not empty');
      146:  copy(p, 'Is subst path');
      147:  copy(p, 'Is join path');
      148:  copy(p, 'Path busy');
      149:  copy(p, 'Is subst target');
      150:  copy(p, 'System trace');
      151:  copy(p, 'Invalid event count');
      152:  copy(p, 'Too many muxwaiters');
      153:  copy(p, 'Invalid list format');
      154:  copy(p, 'Label too long');
      155:  copy(p, 'Too many tcbs');
      156:  copy(p, 'Signal refused');
      157:  copy(p, 'Discarded');
      158:  copy(p, 'Not locked');
      159:  copy(p, 'Bad threadid addr');
      160:  copy(p, 'Bad arguments');
      161:  copy(p, 'Bad pathname');
      162:  copy(p, 'Signal pending');
      164:  copy(p, 'Max thrds reached');
      167:  copy(p, 'Lock failed');
      170:  copy(p, 'Busy');
      173:  copy(p, 'Cancel violation');
      174:  copy(p, 'Atomic locks not supported');
      180:  copy(p, 'Invalid segment number');
      182:  copy(p, 'Invalid ordinal');
      183:  copy(p, 'Already exists');
      186:  copy(p, 'Invalid flag number');
      187:  copy(p, 'Sem not found');
      188:  copy(p, 'Invalid starting codeseg');
      189:  copy(p, 'Invalid stackseg');
      190:  copy(p, 'Invalid moduletype');
      191:  copy(p, 'Invalid exe signature');
      192:  copy(p, 'Exe marked invalid');
      193:  copy(p, 'Bad exe format');
      194:  copy(p, 'Iterated data exceeds 64k');
      195:  copy(p, 'Invalid minallocsize');
      196:  copy(p, 'Dynlink from invalid ring');
      197:  copy(p, 'Iopl not enabled');
      198:  copy(p, 'Invalid segdpl');
      199:  copy(p, 'Autodataseg exceeds 64k');
      200:  copy(p, 'Ring2seg must be movable');
      201:  copy(p, 'Reloc chain xeeds seglim');
      202:  copy(p, 'Infloop in reloc chain');
      203:  copy(p, 'Envvar not found');
      205:  copy(p, 'No signal sent');
      206:  copy(p, 'Filename exceeds range');
      207:  copy(p, 'Ring2 stack in use');
      208:  copy(p, 'Meta expansion too long');
      209:  copy(p, 'Invalid signal number');
      210:  copy(p, 'Thread 1 inactive');
      212:  copy(p, 'Locked');
      214:  copy(p, 'Too many modules');
      215:  copy(p, 'Nesting not allowed');
      230:  copy(p, 'Bad pipe');
      231:  copy(p, 'Pipe busy');
      232:  copy(p, 'No data');
      233:  copy(p, 'Pipe not connected');
      234:  copy(p, 'More data');
      240:  copy(p, 'Vc disconnected');
      254:  copy(p, 'Invalid ea name');
      255:  copy(p, 'Ea list inconsistent');
      259:  copy(p, 'No more items');
      266:  copy(p, 'Cannot copy');
      267:  copy(p, 'Directory');
      275:  copy(p, 'Eas didnt fit');
      276:  copy(p, 'Ea file corrupt');
      277:  copy(p, 'Ea table full');
      278:  copy(p, 'Invalid ea handle');
      282:  copy(p, 'Eas not supported');
      288:  copy(p, 'Not owner');
      298:  copy(p, 'Too many posts');
      317:  copy(p, 'Mr mid not found');
      487:  copy(p, 'Invalid address');
      534:  copy(p, 'Arithmetic overflow');
      535:  copy(p, 'Pipe connected');
      536:  copy(p, 'Pipe listening');
      994:  copy(p, 'Ea access denied');
      995:  copy(p, 'Operation aborted');
      996:  copy(p, 'Io incomplete');
      997:  copy(p, 'Io pending');
      998:  copy(p, 'Noaccess');
      999:  copy(p, 'Swaperror');
      1001: copy(p, 'Stack overflow');
      1002: copy(p, 'Invalid message');
      1003: copy(p, 'Can not complete');
      1004: copy(p, 'Invalid flags');
      1005: copy(p, 'Unrecognized volume');
      1006: copy(p, 'File invalid');
      1007: copy(p, 'Fullscreen mode');
      1008: copy(p, 'No token');
      1009: copy(p, 'Baddb');
      1010: copy(p, 'Badkey');
      1011: copy(p, 'Cantopen');
      1012: copy(p, 'Cantread');
      1013: copy(p, 'Cantwrite');
      1014: copy(p, 'Registry recovered');
      1015: copy(p, 'Registry corrupt');
      1016: copy(p, 'Registry io failed');
      1017: copy(p, 'Not registry file');
      1018: copy(p, 'Key deleted');
      1019: copy(p, 'No log space');
      1020: copy(p, 'Key has children');
      1021: copy(p, 'Child must be volatile');
      1022: copy(p, 'Notify enum dir');
      1051: copy(p, 'Dependent services running');
      1052: copy(p, 'Invalid service control');
      1053: copy(p, 'Service request timeout');
      1054: copy(p, 'Service no thread');
      1055: copy(p, 'Service database locked');
      1056: copy(p, 'Service already running');
      1057: copy(p, 'Invalid service account');
      1058: copy(p, 'Service disabled');
      1059: copy(p, 'Circular dependency');
      1060: copy(p, 'Service does not exist');
      1061: copy(p, 'Service cannot accept ctrl');
      1062: copy(p, 'Service not active');
      1063: copy(p, 'Failed service controller connect');
      1064: copy(p, 'Exception in service');
      1065: copy(p, 'Database does not exist');
      1066: copy(p, 'Service specific error');
      1067: copy(p, 'Process aborted');
      1068: copy(p, 'Service dependency fail');
      1069: copy(p, 'Service logon failed');
      1070: copy(p, 'Service start hang');
      1071: copy(p, 'Invalid service lock');
      1072: copy(p, 'Service marked for delete');
      1073: copy(p, 'Service exists');
      1074: copy(p, 'Already running lkg');
      1075: copy(p, 'Service dependency deleted');
      1076: copy(p, 'Boot already accepted');
      1077: copy(p, 'Service never started');
      1078: copy(p, 'Duplicate service name');
      1100: copy(p, 'End of media');
      1101: copy(p, 'Filemark detected');
      1102: copy(p, 'Beginning of media');
      1103: copy(p, 'Setmark detected');
      1104: copy(p, 'No data detected');
      1105: copy(p, 'Partition failure');
      1106: copy(p, 'Invalid block length');
      1107: copy(p, 'Device not partitioned');
      1108: copy(p, 'Unable to lock media');
      1109: copy(p, 'Unable to unload media');
      1110: copy(p, 'Media changed');
      1111: copy(p, 'Bus reset');
      1112: copy(p, 'No media in drive');
      1113: copy(p, 'No unicode translation');
      1114: copy(p, 'Dll init failed');
      1115: copy(p, 'Shutdown in progress');
      1116: copy(p, 'No shutdown in progress');
      1117: copy(p, 'Io device');
      1118: copy(p, 'Serial no device');
      1119: copy(p, 'Irq busy');
      1120: copy(p, 'More writes');
      1121: copy(p, 'Counter timeout');
      1122: copy(p, 'Floppy id mark not found');
      1123: copy(p, 'Floppy wrong cylinder');
      1124: copy(p, 'Floppy unknown error');
      1125: copy(p, 'Floppy bad registers');
      1126: copy(p, 'Disk recalibrate failed');
      1127: copy(p, 'Disk operation failed');
      1128: copy(p, 'Disk reset failed');
      1129: copy(p, 'Eom overflow');
      1130: copy(p, 'Not enough server memory');
      1131: copy(p, 'Possible deadlock');
      1132: copy(p, 'Mapped alignment');
      2202: copy(p, 'Bad username');
      2250: copy(p, 'Not connected');
      2401: copy(p, 'Open files');
      2404: copy(p, 'Device in use');
      1200: copy(p, 'Bad device');
      1201: copy(p, 'Connection unavail');
      1202: copy(p, 'Device already remembered');
      1203: copy(p, 'No net or bad path');
      1204: copy(p, 'Bad provider');
      1205: copy(p, 'Cannot open profile');
      1206: copy(p, 'Bad profile');
      1207: copy(p, 'Not container');
      1208: copy(p, 'Extended error');
      1209: copy(p, 'Invalid groupname');
      1210: copy(p, 'Invalid computername');
      1211: copy(p, 'Invalid eventname');
      1212: copy(p, 'Invalid domainname');
      1213: copy(p, 'Invalid servicename');
      1214: copy(p, 'Invalid netname');
      1215: copy(p, 'Invalid sharename');
      1216: copy(p, 'Invalid passwordname');
      1217: copy(p, 'Invalid messagename');
      1218: copy(p, 'Invalid messagedest');
      1219: copy(p, 'Session credential conflict');
      1220: copy(p, 'Remote session limit exceeded');
      1221: copy(p, 'Dup domainname');
      1222: copy(p, 'No network');
      1300: copy(p, 'Not all assigned');
      1301: copy(p, 'Some not mapped');
      1302: copy(p, 'No quotas for account');
      1303: copy(p, 'Local user session key');
      1304: copy(p, 'Null lm password');
      1305: copy(p, 'Unknown revision');
      1306: copy(p, 'Revision mismatch');
      1307: copy(p, 'Invalid owner');
      1308: copy(p, 'Invalid primary group');
      1309: copy(p, 'No impersonation token');
      1310: copy(p, 'Cant disable mandatory');
      1311: copy(p, 'No logon servers');
      1312: copy(p, 'No such logon session');
      1313: copy(p, 'No such privilege');
      1314: copy(p, 'Privilege not held');
      1315: copy(p, 'Invalid account name');
      1316: copy(p, 'User exists');
      1317: copy(p, 'No such user');
      1318: copy(p, 'Group exists');
      1319: copy(p, 'No such group');
      1320: copy(p, 'Member in group');
      1321: copy(p, 'Member not in group');
      1322: copy(p, 'Last admin');
      1323: copy(p, 'Wrong password');
      1324: copy(p, 'Ill formed password');
      1325: copy(p, 'Password restriction');
      1326: copy(p, 'Logon failure');
      1327: copy(p, 'Account restriction');
      1328: copy(p, 'Invalid logon hours');
      1329: copy(p, 'Invalid workstation');
      1330: copy(p, 'Password expired');
      1331: copy(p, 'Account disabled');
      1332: copy(p, 'None mapped');
      1333: copy(p, 'Too many luids requested');
      1334: copy(p, 'Luids exhausted');
      1335: copy(p, 'Invalid sub authority');
      1336: copy(p, 'Invalid acl');
      1337: copy(p, 'Invalid sid');
      1338: copy(p, 'Invalid security descr');
      1340: copy(p, 'Bad inheritance acl');
      1341: copy(p, 'Server disabled');
      1342: copy(p, 'Server not disabled');
      1343: copy(p, 'Invalid id authority');
      1344: copy(p, 'Allotted space exceeded');
      1345: copy(p, 'Invalid group attributes');
      1346: copy(p, 'Bad impersonation level');
      1347: copy(p, 'Cant open anonymous');
      1348: copy(p, 'Bad validation class');
      1349: copy(p, 'Bad token type');
      1350: copy(p, 'No security on object');
      1351: copy(p, 'Cant access domain info');
      1352: copy(p, 'Invalid server state');
      1353: copy(p, 'Invalid domain state');
      1354: copy(p, 'Invalid domain role');
      1355: copy(p, 'No such domain');
      1356: copy(p, 'Domain exists');
      1357: copy(p, 'Domain limit exceeded');
      1358: copy(p, 'Internal db corruption');
      1359: copy(p, 'Internal error');
      1360: copy(p, 'Generic not mapped');
      1361: copy(p, 'Bad descriptor format');
      1362: copy(p, 'Not logon process');
      1363: copy(p, 'Logon session exists');
      1364: copy(p, 'No such package');
      1365: copy(p, 'Bad logon session state');
      1366: copy(p, 'Logon session collision');
      1367: copy(p, 'Invalid logon type');
      1368: copy(p, 'Cannot impersonate');
      1369: copy(p, 'Rxact invalid state');
      1370: copy(p, 'Rxact commit failure');
      1371: copy(p, 'Special account');
      1372: copy(p, 'Special group');
      1373: copy(p, 'Special user');
      1374: copy(p, 'Members primary group');
      1375: copy(p, 'Token already in use');
      1376: copy(p, 'No such alias');
      1377: copy(p, 'Member not in alias');
      1378: copy(p, 'Member in alias');
      1379: copy(p, 'Alias exists');
      1380: copy(p, 'Logon not granted');
      1381: copy(p, 'Too many secrets');
      1382: copy(p, 'Secret too long');
      1383: copy(p, 'Internal db error');
      1384: copy(p, 'Too many context ids');
      1385: copy(p, 'Logon type not granted');
      1386: copy(p, 'Nt cross encryption required');
      1387: copy(p, 'No such member');
      1388: copy(p, 'Invalid member');
      1389: copy(p, 'Too many sids');
      1390: copy(p, 'Lm cross encryption required');
      1391: copy(p, 'No inheritance');
      1392: copy(p, 'File corrupt');
      1393: copy(p, 'Disk corrupt');
      1394: copy(p, 'No user session key');
      1400: copy(p, 'Invalid window handle');
      1401: copy(p, 'Invalid menu handle');
      1402: copy(p, 'Invalid cursor handle');
      1403: copy(p, 'Invalid accel handle');
      1404: copy(p, 'Invalid hook handle');
      1405: copy(p, 'Invalid dwp handle');
      1406: copy(p, 'Tlw with wschild');
      1407: copy(p, 'Cannot find wnd class');
      1408: copy(p, 'Window of other thread');
      1409: copy(p, 'Hotkey already registered');
      1410: copy(p, 'Class already exists');
      1411: copy(p, 'Class does not exist');
      1412: copy(p, 'Class has windows');
      1413: copy(p, 'Invalid index');
      1414: copy(p, 'Invalid icon handle');
      1415: copy(p, 'Private dialog index');
      1416: copy(p, 'Listbox id not found');
      1417: copy(p, 'No wildcard characters');
      1418: copy(p, 'Clipboard not open');
      1419: copy(p, 'Hotkey not registered');
      1420: copy(p, 'Window not dialog');
      1421: copy(p, 'Control id not found');
      1422: copy(p, 'Invalid combobox message');
      1423: copy(p, 'Window not combobox');
      1424: copy(p, 'Invalid edit height');
      1425: copy(p, 'Dc not found');
      1426: copy(p, 'Invalid hook filter');
      1427: copy(p, 'Invalid filter proc');
      1428: copy(p, 'Hook needs hmod');
      1429: copy(p, 'Global only hook');
      1430: copy(p, 'Journal hook set');
      1431: copy(p, 'Hook not installed');
      1432: copy(p, 'Invalid lb message');
      1433: copy(p, 'Setcount on bad lb');
      1434: copy(p, 'Lb without tabstops');
      1435: copy(p, 'Destroy object of other thread');
      1436: copy(p, 'Child window menu');
      1437: copy(p, 'No system menu');
      1438: copy(p, 'Invalid msgbox style');
      1439: copy(p, 'Invalid spi value');
      1440: copy(p, 'Screen already locked');
      1441: copy(p, 'Hwnds have diff parent');
      1442: copy(p, 'Not child window');
      1443: copy(p, 'Invalid gw command');
      1444: copy(p, 'Invalid thread id');
      1445: copy(p, 'Non mdichild window');
      1446: copy(p, 'Popup already active');
      1447: copy(p, 'No scrollbars');
      1448: copy(p, 'Invalid scrollbar range');
      1449: copy(p, 'Invalid showwin command');
      1500: copy(p, 'Eventlog file corrupt');
      1501: copy(p, 'Eventlog cant start');
      1502: copy(p, 'Log file full');
      1503: copy(p, 'Eventlog file changed');
      1700: copy(p, 'Rpc s invalid string binding');
      1701: copy(p, 'Rpc s wrong kind of binding');
      1702: copy(p, 'Rpc s invalid binding');
      1703: copy(p, 'Rpc s protseq not supported');
      1704: copy(p, 'Rpc s invalid rpc protseq');
      1705: copy(p, 'Rpc s invalid string uuid');
      1706: copy(p, 'Rpc s invalid endpoint format');
      1707: copy(p, 'Rpc s invalid net addr');
      1708: copy(p, 'Rpc s no endpoint found');
      1709: copy(p, 'Rpc s invalid timeout');
      1710: copy(p, 'Rpc s object not found');
      1711: copy(p, 'Rpc s already registered');
      1712: copy(p, 'Rpc s type already registered');
      1713: copy(p, 'Rpc s already listening');
      1714: copy(p, 'Rpc s no protseqs registered');
      1715: copy(p, 'Rpc s not listening');
      1716: copy(p, 'Rpc s unknown mgr type');
      1717: copy(p, 'Rpc s unknown if');
      1718: copy(p, 'Rpc s no bindings');
      1719: copy(p, 'Rpc s no protseqs');
      1720: copy(p, 'Rpc s cant create endpoint');
      1721: copy(p, 'Rpc s out of resources');
      1722: copy(p, 'Rpc s server unavailable');
      1723: copy(p, 'Rpc s server too busy');
      1724: copy(p, 'Rpc s invalid network options');
      1725: copy(p, 'Rpc s no call active');
      1726: copy(p, 'Rpc s call failed');
      1727: copy(p, 'Rpc s call failed dne');
      1728: copy(p, 'Rpc s protocol error');
      1730: copy(p, 'Rpc s unsupported trans syn');
      1732: copy(p, 'Rpc s unsupported type');
      1733: copy(p, 'Rpc s invalid tag');
      1734: copy(p, 'Rpc s invalid bound');
      1735: copy(p, 'Rpc s no entry name');
      1736: copy(p, 'Rpc s invalid name syntax');
      1737: copy(p, 'Rpc s unsupported name syntax');
      1739: copy(p, 'Rpc s uuid no address');
      1740: copy(p, 'Rpc s duplicate endpoint');
      1741: copy(p, 'Rpc s unknown authn type');
      1742: copy(p, 'Rpc s max calls too small');
      1743: copy(p, 'Rpc s string too long');
      1744: copy(p, 'Rpc s protseq not found');
      1745: copy(p, 'Rpc s procnum out of range');
      1746: copy(p, 'Rpc s binding has no auth');
      1747: copy(p, 'Rpc s unknown authn service');
      1748: copy(p, 'Rpc s unknown authn level');
      1749: copy(p, 'Rpc s invalid auth identity');
      1750: copy(p, 'Rpc s unknown authz service');
      1751: copy(p, 'Ept s invalid entry');
      1752: copy(p, 'Ept s cant perform op');
      1753: copy(p, 'Ept s not registered');
      1754: copy(p, 'Rpc s nothing to export');
      1755: copy(p, 'Rpc s incomplete name');
      1756: copy(p, 'Rpc s invalid vers option');
      1757: copy(p, 'Rpc s no more members');
      1758: copy(p, 'Rpc s not all objs unexported');
      1759: copy(p, 'Rpc s interface not found');
      1760: copy(p, 'Rpc s entry already exists');
      1761: copy(p, 'Rpc s entry not found');
      1762: copy(p, 'Rpc s name service unavailable');
      1763: copy(p, 'Rpc s invalid naf id');
      1764: copy(p, 'Rpc s cannot support');
      1765: copy(p, 'Rpc s no context available');
      1766: copy(p, 'Rpc s internal error');
      1767: copy(p, 'Rpc s zero divide');
      1768: copy(p, 'Rpc s address error');
      1769: copy(p, 'Rpc s fp div zero');
      1770: copy(p, 'Rpc s fp underflow');
      1771: copy(p, 'Rpc s fp overflow');
      1772: copy(p, 'Rpc x no more entries');
      1773: copy(p, 'Rpc x ss char trans open fail');
      1774: copy(p, 'Rpc x ss char trans short file');
      1775: copy(p, 'Rpc x ss in null context');
      1777: copy(p, 'Rpc x ss context damaged');
      1778: copy(p, 'Rpc x ss handles mismatch');
      1779: copy(p, 'Rpc x ss cannot get call handle');
      1780: copy(p, 'Rpc x null ref pointer');
      1781: copy(p, 'Rpc x enum value out of range');
      1782: copy(p, 'Rpc x byte count too small');
      1783: copy(p, 'Rpc x bad stub data');
      1784: copy(p, 'Invalid user buffer');
      1785: copy(p, 'Unrecognized media');
      1786: copy(p, 'No trust lsa secret');
      1787: copy(p, 'No trust sam account');
      1788: copy(p, 'Trusted domain failure');
      1789: copy(p, 'Trusted relationship failure');
      1790: copy(p, 'Trust failure');
      1791: copy(p, 'Rpc s call in progress');
      1792: copy(p, 'Netlogon not started');
      1793: copy(p, 'Account expired');
      1794: copy(p, 'Redirector has open handles');
      1795: copy(p, 'Printer driver already installed');
      1796: copy(p, 'Unknown port');
      1797: copy(p, 'Unknown printer driver');
      1798: copy(p, 'Unknown printprocessor');
      1799: copy(p, 'Invalid separator file');
      1800: copy(p, 'Invalid priority');
      1801: copy(p, 'Invalid printer name');
      1802: copy(p, 'Printer already exists');
      1803: copy(p, 'Invalid printer command');
      1804: copy(p, 'Invalid datatype');
      1805: copy(p, 'Invalid environment');
      1806: copy(p, 'Rpc s no more bindings');
      1807: copy(p, 'Nologon interdomain trust account');
      1808: copy(p, 'Nologon workstation trust account');
      1809: copy(p, 'Nologon server trust account');
      1810: copy(p, 'Domain trust inconsistent');
      1811: copy(p, 'Server has open handles');
      1812: copy(p, 'Resource data not found');
      1813: copy(p, 'Resource type not found');
      1814: copy(p, 'Resource name not found');
      1815: copy(p, 'Resource lang not found');
      1816: copy(p, 'Not enough quota');
      1898: copy(p, 'Rpc s group member not found');
      1899: copy(p, 'Ept s cant create');
      1900: copy(p, 'Rpc s invalid object');
      1901: copy(p, 'Invalid time');
      1902: copy(p, 'Invalid form name');
      1903: copy(p, 'Invalid form size');
      1904: copy(p, 'Already waiting');
      1905: copy(p, 'Printer deleted');
      1906: copy(p, 'Invalid printer state');
      6118: copy(p, 'No browser servers found');
                   
   end             
                   
end;               

{ write windows error }

procedure writerr(var f: text; e: integer);

var p: pstring;

begin

   geterr(e, p); { get the corresponding error string }
   write(f, p^); { write that }
   dispose(p) { release it }
                   
end;               
                   
begin              
end.               
