{******************************************************************************
*                                                                             *
*                            POWER TABLE GENERATOR                            *
*                                                                             *
*                             99/3/2 S. A. Moore                              *
*                                                                             *
* Generates a power table for the purposes of finding in-line                 *
* multiplications. This is a series of "add one, double current" operations   *
* that create an equivalent constant multiply.                                *
* We generate 10 such operations over 100 multiply constants. The format of   *
* the table is:                                                               *
*                                                                             *
* fixed powtab: array [1..100, 1..10] of char = array                         *
*                                                                             *
*    '          ',                                                            *
*    'd         ',                                                            *
*    'da        ',                                                            *
*                                                                             *
* etc. "d" stands for "double", "a" stands for "add one". The standard        *
* method for performing the multiplication is to save the original contents   *
* of the multiplicand, then either add the multiplicand to itself (* 2) or    *
* the saved copy (+1).                                                        *
*                                                                             *
* One area I haven't researched is if pulling a copy out of the middle of the *
* sequence and using it later would shorten the sequence.                     *
*                                                                             *
* The table is generated by a routine that searches all the leaves of a       *
* power tree to find the solution, not a particularly fast solution, which    *
* is why we generate a table, I guess.                                        *
*                                                                             *
* This routine was originally used to generate tables for the Z80 compiler    *
* in about 1982 (good programs never die !).                                  *
*                                                                             *
******************************************************************************}

program powtab(output);
 
label 99;
 
const pownum = 10; { number of powers to allow }
      maxnum = 94; { highest 10 place power that can be performed }
 
type powert = (null, addone, timtwo);
 
var powers, finpows : array [1..pownum] of powert;
    powi, maxpwr, sercnt, trgpwr, i : integer;
 
procedure prtser;
 
var i : integer;
 
begin

   if maxpwr = 0 then write('          ') else begin

      for i := 1 to pownum do begin

         if finpows[i] = addone then write('a');
         if finpows[i] = timtwo then write('d');
         if finpows[i] = null then write(' ')

      end

   end

end;
 
procedure genpwr(curpwr, pwrcnt : integer);
 
label 88;
 
procedure enter(p : powert);
 
begin

   if powi > pownum then goto 88;
   powers[powi] := p;
   powi := powi + 1

end;
 
procedure poppwr;
 
begin

   if powi = 1 then begin

      writeln('*** power series overflow');
      goto 99

   end;
   powi := powi - 1;
   powers[powi] := null

end;
 
begin

   sercnt := sercnt + 1;
   if (curpwr * 2) = trgpwr then begin

      if ((pwrcnt + 1) < maxpwr) or (maxpwr = 0) then begin

         enter(timtwo);
         finpows := powers;
         maxpwr := pwrcnt + 1;
         poppwr

      end

   end else begin

      if (curpwr * 2) < trgpwr then begin

         enter(timtwo);
         genpwr(curpwr * 2, pwrcnt + 1);
         poppwr

      end;
      if (curpwr + 1) = trgpwr then begin

         if ((pwrcnt + 1) < maxpwr) or (maxpwr = 0) then begin

            enter(addone);
            finpows := powers;
            maxpwr := pwrcnt + 1;
            poppwr

         end

      end else begin

         enter(addone);
         genpwr(curpwr + 1, pwrcnt + 1);
         poppwr

      end

   end;
   88:;

end;
 
begin

   writeln;
   writeln('{ Multiply powers table -- Generated by powtab.pas }');
   writeln;
   writeln('const maxmlt = 94; { number of multiplies that can be done in 10 places }');
   writeln;
   writeln('fixed powtab: packed array [1..maxmlt, 1..10] of char = array');
   writeln;
   for trgpwr := 1 to maxnum do begin { traverse powers }

      sercnt := 0;
      maxpwr := 0;
      powi := 1;
      for i := 1 to pownum do powers[i] := null;
      write('   ''');
      genpwr(1, 0);
      prtser;
      write('''');
      if trgpwr = maxnum then write(' ') else write(',');
      writeln(' { ', trgpwr:2, ' }')

   end;
   writeln;
   writeln('end;');

   99:; { terminate program }

end.
